### PR TITLE
v1.0.0 beta release 

### PR DESCRIPTION
**Pull request by pratikiran**
The **source code** need to be pushed to the `main` branch before the release. @Saravana200 and @Geethanjali2608 need to **review** before the release and resolve all the conflicts. 
> Remove `DevicePreview` before the release.

### CODE REVIEW

**Review by NitheeshwarBR — APPROVED** [review]
The features are well implemented

fix : change the download button functionality from Boolean states to some timeout functionality

Description: when the ⬇️ ( download) icon is clicked it is switched to ☑️ ( completed) icon , but when the completed icon is clicked then it switches back to ⬇️, instead i would suggest to set timeout function, such that after some particular time the user can download it again

fix : change the icon themes ( purple color ) at the profile page .

**Review by NitheeshwarBR — APPROVED** [review]
I would suggest, to keep the docs updated as in to have a track of all the routes  of all the frontend features and the headers / properties of the frontend features which would enhance the easiness while integrating with the backend

**Review by Geethanjali2608 — APPROVED** [review]

**Review by Saravana200 — COMMENTED** [review]
-change app icon to Broadway communication logo

no more issues for now

**Review by Saravana200 — APPROVED** [review]
approved !!!

**Pull request merged**
